

-- Bảng user
CREATE TABLE "user" (
    user_id BIGINT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    email VARCHAR(255) UNIQUE,
    full_name VARCHAR(255),
    refresh_token TEXT,
    gender varchar(255),
    dob DATE,
	avatar VARCHAR(255),
    status_user varchar(255),
    create_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    update_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    role_id BIGINT
);

-- Bảng role
CREATE TABLE role (
    role_id BIGINT PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL
);

-- Bảng permission
CREATE TABLE permission (
    permission_id BIGINT PRIMARY KEY,
    permission_name VARCHAR(100) NOT NULL
);

-- Bảng role_permission
CREATE TABLE role_permission (
    role_permission_id BIGINT PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES role(role_id),
    FOREIGN KEY (permission_id) REFERENCES permission(permission_id)
);

-- Bảng photo
CREATE TABLE photo (
    photo_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    url TEXT,
    filename VARCHAR(255),
    metadata JSONB,
    deleted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	liked BOOLEAN DEFAULT FALSE,
	update_at TIMESTAMP WITH TIME ZONE,
	is_deleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES "user"(user_id)
);

-- Bảng album
CREATE TABLE album (
    album_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id)
);

-- Bảng album_photo (N-N giữa album và photo)
CREATE TABLE album_photo (
    album_photo_id BIGINT PRIMARY KEY,
    album_id BIGINT NOT NULL,
    photo_id BIGINT NOT NULL,
    FOREIGN KEY (album_id) REFERENCES album(album_id),
    FOREIGN KEY (photo_id) REFERENCES photo(photo_id)
);

-- Bảng shared_album
CREATE TABLE shared_album (
    shared_album_id BIGINT PRIMARY KEY,
    album_id BIGINT NOT NULL,
    shared_with BIGINT NOT NULL, -- user_id được chia sẻ
    permission VARCHAR(20),
    FOREIGN KEY (album_id) REFERENCES album(album_id),
    FOREIGN KEY (shared_with) REFERENCES "user"(user_id)
);

-- Bảng poster
CREATE TABLE poster (
    poster_id BIGINT PRIMARY KEY ,
    title VARCHAR(255),
    content TEXT,
    file_path VARCHAR(255),
    poster_type VARCHAR(255),
	company_name VARCHAR(255),
    create_date DATE DEFAULT CURRENT_DATE,
    update_date DATE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_draft BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    user_id BIGINT,
	owner_id BIGINT NOT NULL,
    post_style_id BIGINT,
    photo_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES "user"(user_id),
    FOREIGN KEY (photo_id) REFERENCES photo(photo_id),
	FOREIGN KEY (owner_id) REFERENCES "user"(user_id)
);

-- Bảng poster_reaction
CREATE TABLE poster_reaction (
    reaction_id BIGINT PRIMARY KEY,
    poster_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction varchar(255),
    create_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	update_date TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    FOREIGN KEY (poster_id) REFERENCES poster(poster_id),
    FOREIGN KEY (user_id) REFERENCES "user"(user_id)
);


ALTER TABLE public.user ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.poster_reaction ALTER COLUMN reaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);